---
# This script contains commands to manage "Profile workflow" and install site from scratch by using installation profile.
- name: Droping drupal database
  mysql_db: name={{ mysql_db }} state=absent login_user={{ mysql_user }} login_password={{ mysql_pass }}

- name: Creating drupal database
  mysql_db: name={{ mysql_db }} state=present login_user={{ mysql_user }} login_password={{ mysql_pass }}

- name: Remove settings.php
  file: name={{ settings_file_path }} state=absent
  sudo: yes
  when: run_installation_process
  
- name: Installing drupal
  sudo: yes
  shell: "{{ php_env_vars }} drush -y si {{ installation_profile_name }} {{ openy_profile_install_settings }} openy_terms_of_use.agree_openy_terms=1 install_configure_form.enable_update_status_emails=NULL --db-url=mysql://{{ mysql_user }}:{{ mysql_pass }}@127.0.0.1:/{{ mysql_db }} --account-name={{ drupal_user }} --account-pass={{ drupal_pass }} --uri={{ site_url }}"
  when: run_installation_process
